#!/bin/sh
# script2: a real program with variables, input, 
#          and control flow

BOOK=phonebook.data
NAME=$1

echo "finding" $NAME "in phonebook"

if grep $NAME $BOOK > /tmp/pb.tmp
then
	echo Entries for $NAME
	cat /tmp/pb.tmp
else
	echo No entries for $NAME
fi
rm /tmp/pb.tmp